# fruit drops
# cherries
[tree_cherry.fruit_data]
    harvest = "cherry"
    positions = [[-14, -28], [0, -18], [13, -28], [-14, -28], [0, -18], [13, -28]]
    seasons = ["spring"]
   	regrow_days = 1

#lemons
[tree_lemon.fruit_data]
	harvest = "lemon"
	positions = [[-13, -28], [0, -20], [14, -28], [-13, -28], [0, -20], [14, -28]]
	seasons = ["spring"]
	regrow_days = 1

# coconuts
[tree_coconut.fruit_data]
	harvest = "coconut"
	positions = [[-5, -61], [-13, -47], [4, -46], [-5, -61], [-13, -47], [4, -46]]
	seasons = ["summer"]
	regrow_days = 1

# pears
[tree_pear.fruit_data]
	harvest = "pear"
	positions = [[-14, -29], [0, -18], [14, -29], [-14, -29], [0, -18], [14, -29]]
	seasons = ["summer"]
	regrow_days = 1

# peaches
[tree_peach.fruit_data]
	harvest = "peach"
	positions = [[-13, -26], [0, -18], [13, -26], [-13, -26], [0, -18], [13, -26]]
	seasons = ["summer"]
	regrow_days = 1

# apples
[tree_apple.fruit_data]
	harvest = "apple"
	positions = [[-12, -28], [0, -19], [14, -28], [-12, -28], [0, -19], [14, -28]]
	seasons = ["fall"]
	regrow_days = 1

# oranges
[tree_orange.fruit_data]
	harvest = "orange"
	positions = [[-15, -33], [0, -27], [15, -33], [-15, -33], [0, -27], [15, -33]]
	seasons = ["fall"]
	regrow_days = 1

# pomegranates
[tree_pomegranate.fruit_data]
	harvest = "pomegranate"
	positions = [[-17, -33], [-1, -27], [13, -33], [-17, -33], [-1, -27], [13, -33]]
	seasons = ["winter"]
	regrow_days = 1

# plum blossoms
[tree_plum_blossom.fruit_data]
	harvest = "plum_blossom"
	positions = [[-15, -30], [0, -46], [15, -30], [-15, -30], [0, -46], [15, -30]]
	seasons = ["winter"]
	regrow_days = 1

# ----------------------------------------
# growth stages

# Cherry growth stage
[tree_cherry]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Lemon growth stage
[tree_lemon]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Coconut growth stage
[tree_coconut]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Pear growth stage
[tree_pear]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Peach growth stage
[tree_peach]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Apple growth stage
[tree_apple]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Orange growth stage
[tree_orange]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Pomegranate growth stage
[tree_pomegranate]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]

# Plum Blossom growth stage
[tree_plum_blossom]
    day_to_stage = [0, 1, 2, 3, 4, 4, 4]
