min_heart_level_for_breeding = 1

# Tier 0
[[production_tiers]]
normal = { count = 1, additional_chance = 0.10 }
golden = { count = 0, additional_chance = 0.0 }
MOMIidentify = { hearts_required = 0 }

# Tier 2
[[production_tiers]]
normal = { count = 1, additional_chance = 0.40 }
golden = { count = 0, additional_chance = 0.05 }
MOMIidentify = { hearts_required = 2 }

# Tier 4
[[production_tiers]]
normal = { count = 2, additional_chance = 0.25 }
golden = { count = 0, additional_chance = 0.05 }
MOMIidentify = { hearts_required = 4 }

# Tier 6
[[production_tiers]]
normal = { count = 3, additional_chance = 0.20 }
golden = { count = 0, additional_chance = 0.05 }
MOMIidentify = { hearts_required = 6 }

# Tier 8
[[production_tiers]]
normal = { count = 3, additional_chance = 0.20 }
golden = { count = 0, additional_chance = 0.10 }
MOMIidentify = { hearts_required = 8 }

# Tier 10
[[production_tiers]]
normal = { count = 4, additional_chance = 0.10 }
golden = { count = 2, additional_chance = 0.15 }
MOMIidentify = { hearts_required = 10 }
